import Head from 'next/head'
import Image from 'next/image'
// components
import { BackgroundImage1, BackgroundImage2, FooterCon, FooterLink, GenerateQuoteButton, GenerateQuoteButtonText, GradientBackgroundCon, QuoteGeneratorCon, QuoteGeneratorInnerCon, QuoteGeneratorSubTitle, QuoteGeneratorTitle, RedSpan } from '@/components/quoteGenerator/quoteGeneratorElement'
// assets
import cloud from "../assets/clouds.png"
import raining from "../assets/rain.png"
import { useEffect, useState } from 'react'
// import '../styles/global.css'
import "./api/_app"
import { updateQuoteAppData } from '@/src/graphql/mutations'
import { quotesQueryName } from '@/src/graphql/queries'
import {GraphQLResult} from '@aws-amplify/api-graphql'
import { API } from 'aws-amplify'
//interface for our Dynamo Db object

interface UpdateQuoteInfoData{
    id: string
  queryName: string
  quotesGenerated: number
  createdAt: string
  updatedAt: string
}
function isGraphQLResultForquotesQueryName(response: any): response is GraphQLResult<{
    QuotesQueryName:{
        items:[UpdateQuoteInfoData]
    }
}>
{return response.data && response.data.QuotesQueryName && response.data.QuotesQueryName.items}
//type guard for our fetch function
export default function Home(){
    const [numberOfQuotes,setNumberOfQuotes] = useState<Number|null>(0)
    //function to fetch our DynamoDb Object (quotes generated)
    const updateQuoteInfo = async () =>{
        try{
            
            //fetch data from the dynamodb using the API 
            const response = await API.graphql<UpdateQuoteInfoData>({
                //info from quries that was autogenerated from src graphql
                query:quotesQueryName,
            authMode:"AWS_IAM",
            //this is the string variable we created in the dynamodb
            variables:{
            queryName:"LIVE"
            },
            })
            console.log('response',response)
            // setNumberOfQuotes()
            //create type guards
            if(!isGraphQLResultForquotesQueryName(response)){
                throw new Error ("UnExpected response from API.graphql");

            }
            if(!response.data){
                throw Error ("Response data is undefined")
            }
            const receivedNumberOfQuotes = response.data.QuotesQueryName.items[0].quotesGenerated;
            setNumberOfQuotes(receivedNumberOfQuotes)
        }catch (error){
            console.log("error getting quote data",error)
        }
    }

    //use useEffect component which invokes the callback after initial rendering (mounting), and on later renderings, if any value inside dependencies has changed
    useEffect(()=>{
        updateQuoteInfo()
    },[])
     
    return(
        <> 
        <Head>
            <title>Inspirational  Quote Generator</title>
            <meta name="description" content="fun project to generate quotes"/>
            <meta name="viewport" content="width=dev-width,initial-scale=1" />
            <link rel="icon" href="/favicon.icon" />
        </Head>
        <GradientBackgroundCon>
        {/* Background images */}
             <BackgroundImage1
             src={cloud}
             height="300"
             alt="cloudbackground1"
             />
             <BackgroundImage2
             src={raining}
             height="300"
             alt="cloudbackground2"
             />
             {/* footer  */}
            <FooterCon>
                 <>
             Quotes Generated:{numberOfQuotes}
             <br />
             Developed with  <RedSpan>❤️</RedSpan> by <FooterLink href="https://my-portfolio-hif6icsrf-davidsonlangat316-gmailcom.vercel.app/"
             target="_blank" rel="noopener noreferrer"> @LangatDenis"
             </FooterLink> 
             </>
            </FooterCon>

        </GradientBackgroundCon>
        {/* Quote Generator modal pop-up */}
        {/* <QuoteGeneratorModal /> */}
        {/* QuoteGenerator */}
        <QuoteGeneratorCon>
            <QuoteGeneratorInnerCon>
                <QuoteGeneratorTitle >
                    Daily Inspiration Generator
                </QuoteGeneratorTitle>
                <QuoteGeneratorSubTitle>
                    Looking for a splash of inspiration? Generate a quote card with a random inspirational quote provided by<FooterLink href="https://zenquotes.io/"
             target="_blank" rel="noopener nooreferrer"> ZenQuotesAPI
              
             </FooterLink> 
                    
                </QuoteGeneratorSubTitle>
                <GenerateQuoteButton>
                    <GenerateQuoteButtonText onClick={null}>Make a Quote
                    </GenerateQuoteButtonText>
                </GenerateQuoteButton>
            </QuoteGeneratorInnerCon>
        </QuoteGeneratorCon>
        </>
           )
    }
